### ISSUE TITLE
Beautify console output

### ISSUE THREAD

**Issue by frickelbruder** [frickelbruder/kickoff#16]
The console error messages need some cosmetics. 
It should basically still look similar, but there need to be some empty lines where appropriate and the section:Rulename hint looks somehow weird

**Comment by skybluesofa** [comment]
Added pull request https://github.com/frickelbruder/kickoff/pull/17 for this issue.

**Comment by frickelbruder** [comment]
Thank you @skybluesofa

**Comment by frickelbruder** [comment]
Followup:
I really like your reorganisation. It is even better, than i envisioned.

Really nice! Thank you!
