### ISSUE TITLE
Validate SSL-Certificate

### ISSUE THREAD

**Issue by frickelbruder** [frickelbruder/kickoff#22]
Add a rule to completely validate the SSL certificate of a webpage

**Comment by frickelbruder** [comment]
Hi @mookman288

thats a nice starting point. What I completely dislike is, that we have to re-request the page inside the rules implementation.
As you pointed out, Guzzle does not seem to provide those infos, so we have to think how we can retrieve those information during the inital request. Maybe Guzzle is the wrong library here. I do not stick with it, if there is an adequate substitute.
Any suggestions?

PS: I moved the comment from the PR, since it is more obvious to find a general discussion on the issue board, than to search in some PRs.

**Comment by mookman288** [comment]
@frickelbruder I believe that stream_context doesn't actually make a second request:

http://stackoverflow.com/a/3081093/1617361

> EDIT: This option is better since it doesn't actually make the HTTP request and does not require allow_url_fopen:

**Comment by frickelbruder** [comment]
@mookman288 

I'm quite sute stream_socket_client opens a new connection:
http://php.net/manual/de/function.stream-socket-client.php

> stream_socket_client — Open Internet or Unix domain socket connection

But as far as I understand, the page content would not be downloaded by the script, because you need to fread the content, which your Rule didn't.

Anyway: 

> Guzzle does provide the information that you need

How could I retrieve them, if I would fetch those information directly in the HTTPRequester?

**Comment by mookman288** [comment]
https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Guzzle.Http.Curl.CurlHandle.html#_getInfo

You can use `CURLINFO_CERTINFO` as your constant with the getInfo function in Guzzle. 

That would allow you to then use the x509 openssl functions in PHP.

**Comment by hanzi** [comment]
This looks great, but it would limit us to Guzzle’s cURL handler since the Stream handler doesn’t seem to support that.

Also, the ‘vanilla’ cURL handler only returns that information for failed requests and not in general. If the request already failed we don’t really need the certificate anymore, though.

**Comment by frickelbruder** [comment]
There is now a simple SSL check rule implemented.
Thanks @hanzi
