### ISSUE TITLE
New command to perform basic SEO check

### ISSUE THREAD

**Issue by frickelbruder** [frickelbruder/kickoff#6]
There should be a new command, to perform basic seo checks on a given website
Example:
```
php ./bin/kickoff.php seocheck http://www.google.com
```

**Comment by micheleorselli** [comment]
Hi @frickelbruder,
which kind of SEO check do you have in mind?

**Comment by frickelbruder** [comment]
Hi @micheleorselli,
 
this should be something like a shortcut command. There are already a bunch of SEO-related rules in the rules.yml defined like Title-Tag-Length or HTTP-Request-time below 1 second (look at /example/seo.yml for example). This should aggregate those rules or any related rules and fire them against the given page. 

This should be used for a quick check only and not an in-depth analysis of the website.

In the end, it would be enough to create 
- a new command
- add a configuration file (analog the existing ymls), where all rules are listed and configured, that will be used for the SEO quickcheck command. 

Since this should be extensible (just adding a rule to the config file extends the new command  with a new rule check), it wouldn't be too bad, if the config file wouldn't already yield all SEO rules one could think of.
