### ISSUE TITLE
Readme.md needs improvement

### ISSUE THREAD

**Issue by frickelbruder** [frickelbruder/kickoff#8]
The readme.md file needs improvement by a native english speaker or at least somebody, who is more fluent in english than me :-)

**Comment by TristanWiley** [comment]
It was pretty good! Updated it for you ^^

**Comment by singh1114** [comment]
thanks.

**Comment by JoshMountain** [comment]
@frickelbruder I have rewritten the Readme.md from the ground up here: https://github.com/frickelbruder/kickoff/pull/11
